fetch("https://jsonplaceholder.typicode.com/posts/1")
.then((response) => response.json())
.then((post)=>post.userId)
// .then((re)=>console.log(re))
.then((userId)=>"https://jsonplaceholder.typicode.com/posts/" + userId)
.then((url) =>fetch(url))
.then((response) => response.json())
.then((user) => console.log("user : ", user))
.catch((error) => console.log("error: ",error))